---

name: 'dbsql_dbt_tpch'
version: '1.0.0'
config-version: 2

profile: 'sql_endpoints'

vars:
  scalefactor: 10
  benchmark: 100
  stage: stagename
  stagingschema: tpcdi_raw_data
  # bucketname: bucketname  # bigquery, redshift only
  storageaccountname: synapsemigrationdemoadls
  catalog: tpcdi
  prodschema: tpcdi_100_dbsql_100

model-paths: ["Databricks/models/main"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbsql_dbt_tpch', 'dbt_utils']
models:
  +start: Jan 1 2000
