sql_endpoints:
  outputs:

    # Use this if connecting to a hosted spark (e.g. Databricks)
    dev:
      type: databricks
      method: http
      #catalog: financeclone
      schema: rstpcdi
      host: e2-demo-field-eng.cloud.databricks.com

      token: <insertokenhere>
       
      # optional
      #http_path: /sql/1.0/endpoints/ead10bf07050390f
      http_path: /sql/1.0/warehouses/ead10bf07050390f



  target: dev
