sql_endpoints:
  target: snowflake

  outputs:

    snowflake:
      type: snowflake
      account: account

      # User/password auth
      user: user
      password: password

      role: "role"
      database: "database" 
      warehouse: "warehouse" 
      schema: "schema"
      threads: 25
      client_session_keep_alive: False

      

    databricks:
      type: databricks
      method: http
      catalog: catalog
      schema: schema
      threads: 25
      host: host
      token: token
      http_path: path
      
    redshift:
      type: redshift
      dbname: db
      host: host
      cluster_id: id
      method: iam
      port: 5439
      schema: schema
      threads: 25
      iam_profile: profile
      user: user
      region: region

    synapse:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: server
      port: 1433
      encrypt: true
      trust_cert: true
      database: database
      schema: schema
      authentication: CLI
      threads: 25

    bigquery:
      type: bigquery
      method: service-account
      project: project
      dataset: dataset
      threads: 25
      priority: interactive
      location: location
      keyfile: "User/keyfile"    
      
