sql_endpoints:
  target: dev
  outputs:
    # Use this if connecting to a hosted spark (e.g. Databricks)
    dev:
      type: databricks
      method: http
      catalog: hive_metastore
      schema: insertschemahere
      threads: 100
      host: inserthosthere
      token: insertokenhere
      http_path: insertpathhere
      
