version: 2

sources:
  - name: tpcdi
    schema: rstpcdiprod
    
    tables:
    
      - name: BatchDate
      - name: CashTransactionHistory

      - name: DailyMarketHistorical
      
      - name: DimDate
      - name: DimTime

      - name: HR
      - name: HoldingHistory
      
      - name: Industry
     
      - name: StatusType
      - name: TaxRate
      - name: TradeHistory
      - name: TradeHistoryRaw
      
      - name: TradeType
      - name: WatchHistory
      
  - name: tpcdidev
    schema: rstpcdistg
    tables:
      - name: AccountIncremental
      - name: CashTransactionIncremental
      - name: CustomerIncremental
      - name: DailyMarketIncremental
      - name: HoldingIncremental
      - name: TradeIncremental
      - name: WatchIncremental
      - name: FinWire 
      - name: ProspectRaw






